export const products = [
  { id: "101", name: "apple", price: 5 },
  { id: "102", name: "banana", price: 10 },
  { id: "103", name: "pear", price: 15 },
  { id: "104", name: "orange", price: 8 },
  { id: "105", name: "strawberry", price: 12 },
  { id: "106", name: "blueberry", price: 7 },
  { id: "107", name: "cherry", price: 9 },
  { id: "108", name: "kiwi", price: 6 },
  { id: "109", name: "mango", price: 14 },
  { id: "110", name: "pineapple", price: 10 },
  { id: "111", name: "watermelon", price: 18 },
  { id: "112", name: "grapefruit", price: 11 },
  { id: "113", name: "lemon", price: 4 },
  { id: "114", name: "lime", price: 3 },
  { id: "115", name: "peach", price: 13 },
  { id: "116", name: "apricot", price: 7 },
  { id: "117", name: "plum", price: 8 },
  { id: "118", name: "nectarine", price: 9 },
  { id: "119", name: "raspberry", price: 5 },
  { id: "120", name: "blackberry", price: 6 },
  { id: "121", name: "cranberry", price: 4 },
  { id: "122", name: "pomegranate", price: 15 },
  { id: "123", name: "coconut", price: 12 },
  { id: "124", name: "guava", price: 11 },
  { id: "125", name: "fig", price: 9 },
  { id: "126", name: "date", price: 8 },
  { id: "127", name: "passion fruit", price: 14 },
  { id: "128", name: "kiwifruit", price: 10 },
  { id: "129", name: "cantaloupe", price: 16 },
  { id: "130", name: "honeydew", price: 14 },
  { id: "131", name: "papaya", price: 13 },
  { id: "132", name: "dragon fruit", price: 20 },
  { id: "133", name: "persimmon", price: 12 },
  { id: "134", name: "kiwi berry", price: 9 },
  { id: "135", name: "star fruit", price: 8 },
  { id: "136", name: "mulberry", price: 6 },
  { id: "137", name: "boysenberry", price: 7 },
  { id: "138", name: "elderberry", price: 5 },
  { id: "139", name: "rhubarb", price: 3 },
  { id: "140", name: "tangerine", price: 7 },
  { id: "141", name: "clementine", price: 5 },
  { id: "142", name: "grapefruit", price: 6 },
  { id: "143", name: "blood orange", price: 8 },
  { id: "144", name: "mandarin orange", price: 5 },
  { id: "145", name: "kumquat", price: 4 },
  { id: "146", name: "pomelo", price: 10 },
  { id: "147", name: "ugli fruit", price: 9 },
  { id: "148", name: "passionfruit", price: 12 },
  { id: "149", name: "jackfruit", price: 15 },
  { id: "150", name: "soursop", price: 18 },
];
